const data = {
    products:[
        {
            _id:'1',
            name:'Roupa Cara 1',
            category:'Shirts',
            image:'/images/Fig 1.png',
            price:100,
            brand:'Supreme',
            rating:5.0,
            numReviews:10,
            description:'peguei da net',
        },
        {
            _id:'2',
            name:'Roupa Cara 2',
            category:'Shirts',
            image:'/images/Fig 2.png',
            price:1200,
            brand:'Supreme',
            rating:4.5,
            numReviews:10,
            description:'peguei da net',
        },
        {
            _id:'3',
            name:'Roupa Cara 3',
            category:'Shirts',
            image:'/images/Fig 3.png',
            price:10,
            brand:'Supreme',
            rating:4.5,
            numReviews:10,
            description:'peguei da net',
        },
        {
            _id:'4',
            name:'Roupa Cara 4',
            category:'Shirts',
            image:'/images/Fig 4.png',
            price:20,
            brand:'Supreme',
            rating:5.0,
            numReviews:10,
            description:'peguei da net',
        },
        {
            _id:'5',
            name:'Roupa Cara 5',
            category:'Shirts',
            image:'/images/Fig 5.png',
            price:66,
            brand:'Supreme',
            rating:4.0,
            numReviews:10,
            description:'peguei da net',
        },
        {
            _id:'6',
            name:'Roupa Cara 6',
            category:'Shirts',
            image:'/images/Fig 6.png',
            price:85.5,
            brand:'Supreme',
            rating:1.0,
            numReviews:10,
            description:'peguei da net',
        },
    ]
}

export default data;